export const breadcrumbItems = {
    dashboard: { title: 'Dashboard', href: route('dashboard') },
    uamUsers: { title: 'Users', href: route('uam.users.index') },
    uamRoles: { title: 'Roles', href: route('uam.roles.index') },
    uamPermissions: { title: 'Permissions', href: route('uam.permissions.index') },
    configurationBranches: { title: 'Branches', href: route('configuration.branches.index') },
    configurationCompanies: { title: 'Companies', href: route('configuration.companies.index') },
    configurationDivisions: { title: 'Divisions', href: route('configuration.divisions.index') },
    configurationDepartments: { title: 'Departments', href: route('configuration.departments.index') },
    configurationUnits: { title: 'Units', href: route('configuration.units.index') },
    configurationDesignations: { title: 'Designations', href: route('configuration.designations.index') },
    configurationPositionGroups: { title: 'Position Groups', href: route('configuration.position-groups.index') },
    configurationPositions: { title: 'Positions', href: route('configuration.positions.index') },
    configurationHrbps: { title: 'HRBP', href: route('configuration.hrbps.index') },
    configurationApprovalLevels: { title: 'Approval Levels', href: route('configuration.approval-levels.index') },
    configurationApprovalFlows: { title: 'Approval Flows', href: route('configuration.approval-flows.index') },
    employeeEmployees: { title: 'Employees', href: route('employee.employees.index') },
    payrollSalaryHeads: { title: 'Salary Heads', href: route('payroll.salary-heads.index') },
    payrollSalaryStructures: { title: 'Salary Structures', href: route('payroll.salary-structures.index') },
    payrollEmployeeSalaryProfiles: { title: 'Employee Salary Profiles', href: route('payroll.employee-salary-profiles.index') },
    payrollSalaryDisbursementBatches: { title: 'Salary Disbursement', href: route('payroll.salary-disbursement-batches.index') },
    notificationIndex: { title: 'Notifications', href: route('notification.index') },
    productCategories: { title: 'Categories', href: route('product.categories.index') },
    productBrands: { title: 'Brands', href: route('product.brands.index') },
    productUnits: { title: 'Units', href: route('product.units.index') },
    productProducts: { title: 'Products', href: route('product.products.index') },
};
